services:
  web:
    build:
      context: .
      dockerfile: app.dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 3333
    container_name: shifak-fastapi
    volumes:
      - ./:/usr/src/app
    ports:
      - "3333:3333"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0